[[Gzip]]
arch = "aarch64"
git-tree-sha1 = "6903793fd43c44a21b484d7a39d556dbd33321bd"
os = "macos"

    [[Gzip.download]]
    sha256 = "c429c10113e955eb7b1739cb465075f359ef9a8eece947ed72c54bdf02a62d29"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.aarch64-apple-darwin.tar.gz"
[[Gzip]]
arch = "aarch64"
git-tree-sha1 = "242499dfda5dba44418f5bffd65cae3ec1dc3e75"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "399a248c42902368796dc5a666481dd35bd50ae1c25126df78f5305a2b14775d"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.aarch64-linux-gnu.tar.gz"
[[Gzip]]
arch = "aarch64"
git-tree-sha1 = "af909f569a0884787183896c221df0574883d380"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "6a669cf3b2413259a1685280c023de158c32484e66ee3a4bd8dc6fc1074cee7a"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.aarch64-linux-musl.tar.gz"
[[Gzip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "16c44c7e3cc1868a5c3b6a7833d1b5d5861e0102"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "ce4a91b6df2d582323e8123f4567b631d98a38c9a2592f0f2ee801958231a0ab"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.armv6l-linux-gnueabihf.tar.gz"
[[Gzip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bd30d5fd292939017e38a681a376c24441a2460d"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "c185af12336f68512f21929fff75322b8b098cf531348a517b6411ad7e972983"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.armv6l-linux-musleabihf.tar.gz"
[[Gzip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5b34ae81b9e7a29088186cf49012b6706ede1caa"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "719d50a9220f46338f6a1b8983cff1a8840923b353ce16d3f81b998228291f07"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.armv7l-linux-gnueabihf.tar.gz"
[[Gzip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "050ee5fad1125226996343431eea632a4d2075d3"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "b3697527af9ed0f8ea329bedaec7881099cf4d5c329a7e8c523df06d4274e406"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.armv7l-linux-musleabihf.tar.gz"
[[Gzip]]
arch = "i686"
git-tree-sha1 = "94401e05714f04abfc9e9f45b7062252e448833f"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "f5de87316cd7fb62bbaecb3e0a5cf005fc91675cd8de9ff5d3872de3a22acafe"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.i686-linux-gnu.tar.gz"
[[Gzip]]
arch = "i686"
git-tree-sha1 = "2ca8b61210dac6d26a07e2b2e6b7d9c6b3211fcc"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "b75c9272b4867fa1db5a81e753a627864baa23025d6bac6dfcd94e5d338cac44"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.i686-linux-musl.tar.gz"
[[Gzip]]
arch = "i686"
git-tree-sha1 = "9fd9247e06d2872c03aa6182a166268de6c050ec"
os = "windows"

    [[Gzip.download]]
    sha256 = "be626d8422f2d1a99e60a11d9ad898831b3832d33ed5189370eba8e36ce2d232"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.i686-w64-mingw32.tar.gz"
[[Gzip]]
arch = "powerpc64le"
git-tree-sha1 = "ad8cbf3858a8559e7f651fa058fa6b64497086c7"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "10511dc5020d48fc11fae67bb00963d7bc7f2fb19886e9a3a905e1bab4411300"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.powerpc64le-linux-gnu.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "7d368573d37a2c7fbe8beafd66b729f8eb0e37b3"
os = "macos"

    [[Gzip.download]]
    sha256 = "f6f39a887f11b80f54c466e816fc0e24c7277d24f0c5e174f52e12aa394ad233"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.x86_64-apple-darwin.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "ea5e8c952567cd8aefcef08662faca62f7b23aa7"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "f4603af6cdd777b89b3233c8e5a93754a80e1249f9f8a660afb085320a9dc82a"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.x86_64-linux-gnu.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "f6184084ea0c84b877a50c924f8d3d78d46667df"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "8469ae0ae5ce4262331742377364c8e809eca27d74b9cc5504000c035e6a664d"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.x86_64-linux-musl.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "e8a1343bbbdc7b23c1ff550b942b4044258a0d6d"
os = "freebsd"

    [[Gzip.download]]
    sha256 = "945aeb4bc5f2061d7afa953166cbd9b726a4f03b89c7a9755013c084a0d27e39"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.x86_64-unknown-freebsd.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "9769d7d482830986736a8f8f0912c3f9f4fd8378"
os = "windows"

    [[Gzip.download]]
    sha256 = "53d32e58179b4561cb1608d3834ae0ef6fc6b03365940b8a364db4b216fb0a84"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.13.0+0/Gzip.v1.13.0.x86_64-w64-mingw32.tar.gz"
