[[Gzip]]
arch = "aarch64"
git-tree-sha1 = "6525ac46fb9dc8a04a7a45560e34259ed21cb282"
os = "macos"

    [[Gzip.download]]
    sha256 = "a93f174f5a94a7a182656075e149dfd75b86be4d28475cfe0d65dc23f183bb0e"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.aarch64-apple-darwin.tar.gz"
[[Gzip]]
arch = "aarch64"
git-tree-sha1 = "ce8cd2bbc79f8758c7b317617d57b206e85d9896"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "a7489f9ffaf983901f47364b8f0880af7e0915d909a82be915a491835bf2655b"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.aarch64-linux-gnu.tar.gz"
[[Gzip]]
arch = "aarch64"
git-tree-sha1 = "f243fce55f31935bc2f0d0df42d09425ea772154"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "71a015cea14749e7677fdb9bd4be57b14eb051f9facf96ad43d89c5d6eb46cb7"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.aarch64-linux-musl.tar.gz"
[[Gzip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0b2d48d918af675cb91333a7d0af08593d810d08"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "f233fbeecebf45936a7e5271d2316446467a670e38e40277c3a34ed65ab6a193"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.armv6l-linux-gnueabihf.tar.gz"
[[Gzip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0ff7de294534f2dabfe196e757d080a59fa69999"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "b0ccd0fd614ac9e98752fa57370dd62f4e09334c1f491de9e5f93cbe384de02a"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.armv6l-linux-musleabihf.tar.gz"
[[Gzip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cbcbccee1dac0850e5f70dffcdbca6a4a4525815"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "cabdbcf575957f5a0bcafced113af59236e82965d82e5efe168a7125ae98e921"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.armv7l-linux-gnueabihf.tar.gz"
[[Gzip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7257c8d0b51b957a4f03d7415496c55d7ea1620e"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "530c3bf95fcb0328aee60ad27725bb5f49f254a10c5462367e2e565f53793bc4"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.armv7l-linux-musleabihf.tar.gz"
[[Gzip]]
arch = "i686"
git-tree-sha1 = "7804d52a09bffb7e7fec74e24462600cf6f36c8d"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "304ab69539595d2717f4e80e2a318174aff492d135e2f61c8ea1cd7563a71a12"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.i686-linux-gnu.tar.gz"
[[Gzip]]
arch = "i686"
git-tree-sha1 = "ff7a13bf07a62bbd665e761bf645386b7a6fc470"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "21740a8ba56103edf885a75ec47635cc771aa8c29de984537331660c4124d329"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.i686-linux-musl.tar.gz"
[[Gzip]]
arch = "i686"
git-tree-sha1 = "2b2c53b4151987a8b4553fc137c7e3f74b3e6206"
os = "windows"

    [[Gzip.download]]
    sha256 = "0744188e00d2a2f5f98a1c0af196741ce9746575a90fc0e14634d64ba2678b6b"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.i686-w64-mingw32.tar.gz"
[[Gzip]]
arch = "powerpc64le"
git-tree-sha1 = "77c6b4c4f8511c56b3cde9be5e7e1589cff1f34b"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "6e0ede9478b3b4780635f3110f15c2bd4da6ad5555462f8dcf3f84d312a3847b"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.powerpc64le-linux-gnu.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "1a5e0a788e0fa61b124c4f02eb1ee2a66d26bbf7"
os = "macos"

    [[Gzip.download]]
    sha256 = "09a796694247003c7fc48dd52db6c21779767e03ac8d63277ff328217bd109e5"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.x86_64-apple-darwin.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "b2806e0e3bc760b09f329ecb757149d774c1952c"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "b24fdfb57729c4149491d4baa42fe5448a6648c60b1f4c689157a4543ba826c7"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.x86_64-linux-gnu.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "52fd923c8ac3fd8d9132865bd11a1d198016d1cf"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "f81ae3c8cf63927d91528e1f8fa5d9ce7b18c4a6fef484c1d6f0685128d618cc"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.x86_64-linux-musl.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "60513d4b51ee818b4010d03d2c86c3e87fb3c4e9"
os = "freebsd"

    [[Gzip.download]]
    sha256 = "cc37c698735602d2607d554d648fcac2f37f93a6032e0e7dcfc32a6970abb7b4"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.x86_64-unknown-freebsd.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "aaf4399b4bc788ade4d02828f18625793c0dc555"
os = "windows"

    [[Gzip.download]]
    sha256 = "836491367aaf95fb2b602ad1a2d546e58a734e5c7674eb70e6b5291330637a15"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.12.0+0/Gzip.v1.12.0.x86_64-w64-mingw32.tar.gz"
