[[Gzip]]
arch = "aarch64"
git-tree-sha1 = "0432bbdcccdb87dbf88505f441b87830226f65eb"
os = "macos"

    [[Gzip.download]]
    sha256 = "bde92626b9acd5ecb25efa8da85d3d7f72504b34d252f3f25cef3890275c5afe"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.aarch64-apple-darwin.tar.gz"
[[Gzip]]
arch = "aarch64"
git-tree-sha1 = "53b9e1d818565f7a148eae968cc0759c552c100b"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "07fab01618db0b30d0e6f84aa22ea0c679da9bc3a46ddd60610234f76239f872"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.aarch64-linux-gnu.tar.gz"
[[Gzip]]
arch = "aarch64"
git-tree-sha1 = "b10ae74b7258466db782d77435d927aa68300c61"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "426ab9eec7bdc99926c73c36955d3ce636686a2521b4f8df4e304d4d37681aed"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.aarch64-linux-musl.tar.gz"
[[Gzip]]
arch = "aarch64"
git-tree-sha1 = "b02000c88fce602da8255bd5867b449f3800822e"
os = "freebsd"

    [[Gzip.download]]
    sha256 = "686968a210d2f44d631e168d39e47a7b7f44aa6ab2a352927579e38bf814dedf"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.aarch64-unknown-freebsd.tar.gz"
[[Gzip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "075e3a89ce990a62e7fa9f7ee9700bfb4800ef08"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "3ab96f0e53b45cb5650ff9c4f0856f10452503a9878ed6ef459e04ba11d6037e"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.armv6l-linux-gnueabihf.tar.gz"
[[Gzip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c6fb300ba07f54761eac7d0b90c4fb1fe81d04c"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "4ba0aad5e28d9ab6bd767e0a8ba45f251da916001876b10446b2f337c603b036"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.armv6l-linux-musleabihf.tar.gz"
[[Gzip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f4be4e6e9e1ebc2df294f2e7b6aa5cd8c9a32722"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "3b1391e456678685960b32114f14f1dbd8a4876c67aeef2333a551abea18527f"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.armv7l-linux-gnueabihf.tar.gz"
[[Gzip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1b11bce98ac0f7b923956b229ffbf86990f75335"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "915b86a029da4451263a8dc37fc96aa4b0891c3d735ad5a4b9b53cb3d328a953"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.armv7l-linux-musleabihf.tar.gz"
[[Gzip]]
arch = "i686"
git-tree-sha1 = "d39e1f268f619010e4a02debce5268d7eac7197b"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "4e51bb93e9fa602c052400f8e5b1082ca11d2bdcf396cb9b11170e77e2aa1b27"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.i686-linux-gnu.tar.gz"
[[Gzip]]
arch = "i686"
git-tree-sha1 = "ef1520211263937cd87650761d610c64392d4c97"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "92a68eceefbbc33961cb2001f29a5573ccda67127cf596170931b2efe2ef5413"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.i686-linux-musl.tar.gz"
[[Gzip]]
arch = "i686"
git-tree-sha1 = "4ea1c31f029e5500d999ffca4e34bd3fac88a76e"
os = "windows"

    [[Gzip.download]]
    sha256 = "0cf78d3158d5cc1eb2165e63d56cb7ac180caa8e1b3db8bd14fa68f04029fd12"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.i686-w64-mingw32.tar.gz"
[[Gzip]]
arch = "powerpc64le"
git-tree-sha1 = "9df0165aa49697f6dd4c9a2b805a2343e10549f5"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "be3795811a3c48d398f2f63a2df97997ee0bf02cdc0cb5ac17f7298b8b051e37"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.powerpc64le-linux-gnu.tar.gz"
[[Gzip]]
arch = "riscv64"
git-tree-sha1 = "ffdfa50159ae1e645ea4a61d8eaf31fc90a9d9e6"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "74e1959ab35d23c6cf5e94cb79ffa20e283cea24b7c8da428cda4a15518d5cdc"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.riscv64-linux-gnu.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "20d19d5c3daa6f53ae01a61118ea1e28468005ea"
os = "macos"

    [[Gzip.download]]
    sha256 = "1497f2c044527773cc8d8d6904e7697208bb1feb75eab147d7287c114d35e018"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.x86_64-apple-darwin.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "642c712b6c3ef74734b00cdd608aeaed724d0f35"
libc = "glibc"
os = "linux"

    [[Gzip.download]]
    sha256 = "889392256661620c891c7ed53c49701764d9449ffe33b9ed8aa44d989ec8d070"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.x86_64-linux-gnu.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "81c77b2363f3b6a325495a86e9fb246125618ad5"
libc = "musl"
os = "linux"

    [[Gzip.download]]
    sha256 = "f060610036770bb828fd33e9b44a7fa463a417c8916211ca6b1fa26572a5efd2"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.x86_64-linux-musl.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "1e50c731cd5eb071e4d560fcc6617bf45a100e1c"
os = "freebsd"

    [[Gzip.download]]
    sha256 = "fbb5b32d2eb12b6f90d0ad2705007d6ad30f3bc5c1a44d0018f84c9f474a92db"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.x86_64-unknown-freebsd.tar.gz"
[[Gzip]]
arch = "x86_64"
git-tree-sha1 = "78dba7d2c33db2179d165f1171a4256732af8cb1"
os = "windows"

    [[Gzip.download]]
    sha256 = "cf185f3bbe17a84e5469ed41d9656d5dfffdec5f6d154e8bea589fff78f195d5"
    url = "https://github.com/JuliaBinaryWrappers/Gzip_jll.jl/releases/download/Gzip-v1.14.0+0/Gzip.v1.14.0.x86_64-w64-mingw32.tar.gz"
