# Autogenerated wrapper script for Gzip_jll for i686-w64-mingw32
export gzip

JLLWrappers.@generate_wrapper_header("Gzip")
JLLWrappers.@declare_executable_product(gzip)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        gzip,
        "bin\\gzip.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
